### ISSUE TITLE
Output data: labelled_matrix with label on both rows and columns

### ISSUE THREAD

**Issue by juritaborri** [aremazeilles/eurobench_documentation#44]
Hi,
for some PIs, I need to have as output a labelled_matrix with labels on both rows and columns.
As an example:
![Cattura](https://user-images.githubusercontent.com/63415341/80715305-7358aa80-8af6-11ea-9534-e5d8b9c75b22.PNG)

How have I to arrange such output in the .yaml file?

**Comment by aremazeilles** [comment]
The inter-run aggregation is said to be mean + std.
That would thus be a 3*3 matrix for the mean plus a 3*3 matrix for the std?

Is there a chance you get only part of the information (no pelvis, or column V)?

I would like to distinguish cases where the content is always fixed ( so that the description of each row /column naming could be part of the PI description), and cases where the result PI may change across trial, so that labelling is mandatory to know to what refers a column / row.

If we will always have a 3*3 matrix, it may not be required to place the label in the PI file?

Then additional question: how do you usually visually compare two of these matrices?

**Comment by juritaborri** [comment]
Yes two 3x3 matrices are the output after inter-run aggregation.
In the manual routine that I am preparing, for the sinusoidal perturbation program I will highligth that it must be applied only if the sensorization of those three segments is possible and if subjects can be subjected to perturbation in those directions. Thus, yes the label are always the same for Gain Index and phase shift. Conversely, for the Range of Motion computed in perturbation protocol the direction are alwys the same but the computed angle could be different.

If it is ok for you, I can remove the labels from Gain Index and Phase Shift and put only the label related to the angles in the ROMp.

As the comparison: greater is the mean value, lower is the ability of subject to react to sinusoidal perturbation; greater is the std, greater is the subject variability in reacting. In the software routine manual, I will consider also a paragraph for suggesting the comparison of the PI.

**Comment by aremazeilles** [comment]
Ok so if the matrix is always the same there might not be any need to label the matrix in the file.
Handling a double matrix as an output PI experiment may be tricky. 

What is your opinion @alfonsotecnalia

**Comment by alfonsotecnalia** [comment]
Sorry because I have missed some conversations and probably I do not completely understand the needs. Is there any special reason for storing a 3x3 matrix as result and not 9 scalars?

Vector and matrix components where thought for those algorithms which had temporal sequence(s) of one (vector) of more (matrix) components as output. Then you applied a mean/std to the whole temporal sequence(s) to extract a unique meaningful value for the component(s). 

Here the intention is to store unique values of different components, isn't it? So when you talk about applying a mean/std to you are thinking about doing it for all of the components in the matrix individually (something like a dot_mean).

Two options:
- Generate 9 scalar files instead of 1 matrix. This would be compatible with the current version of the PIManager. 
- Generate a unique file. I find it more interesting and flexible. But we would have to think a little bit more of how aggregations should be specified and handled by the PIManager.

I would go with the second option but need some time to think how to carry out it.

**Comment by aremazeilles** [comment]
I will close that issue, as we are proposing new output format, in which (see #62) vector of matrix is proposed. 
If you have the labels of each column, then it can be added to the PI file.
We could discuss later on, on how aggregation could be computed on such type of PI.
