### ISSUE TITLE
file naming

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/eurobench_documentation#48]
In the document, we repeat always something like:

**Name of the file**: subject_N_run_R_gaitEvents  where  N = subject’s number and R= run number.
Use appropriate leading zeros for R and N to ensure proper ordering of files.

In #4 discussion, we also mentioned that conditions could also change during the experimentation. So I think we should provide at the bottom a definition common to all:

* We assume an experiment can involve N subjects
* Several conditions C can be tested in a given experiment (like slope of 10 deg, slope of 15, 20, ...)
* The subject conduct M repetitions or runs of the same conditions

So that the captured files should follow the pattern: `subject_N_cond_C_run_R_dataname.csv`, together with the testbed configuration files `cond_C_testbed.yaml`.

If one of the _factor_ elements is not multiple in the protocol / Experiment, then it can be omitted from the naming:

* if only a subject is involved, then `subject_N_` files can be omitted and the datafiles are deduced to: `cond_C_run_R_dataName.csv`
* if a single configuration is tested, then a single testbed.yaml file is provided, and data files are named:  `subject_N_run_R_dataName.csv`
* if a single run s captured per condition (even though this is not the preferred scheme), then datafiles are named: `cond_C_subject_N_dataName.csv`
* In a particuliar experimen involving a unique subject, with a single run, and unique configuration, then the datafilenames would be reduced to `dataName.csv`

Open points still to clarify?

* what should be the outter field: condition or subject (in the naming for instance)
* Should the configuration parameters common to all subject (all go through cond1, then cond2, ...), or can we have some parameters that change from a subject to another?
* is the name `cond` appropriate ? Or `configuration` ? .... I used the term `controlled_variables` in the template spec, but I don't have clear what would be the most evident here.

ping @alfonsotecnalia

**Comment by alfonsotecnalia** [comment]
>     * is the name `cond` appropriate ? Or `configuration` ?

I was already writing the code for the PIManager for handling this. I have had the same problem with the nomenclature. The name of the branch is `experiment_condition` but inside the code I look for files matching `config_XX`. I would discard `controlled_variables` because the problems of understading we are having. If we are thinking in a unique file for both conditions and equipments configurations I would say to use `config` or `configuratio` , if different then `condition`.


>     * what should be the outter field: condition or subject (in the naming for instance)

I would say it is more important the condition than the subject so `condition` should go in the outer field. At some momment I was thiking in includig the subject in the file and avoid having 'subject_S' in all the files but that could lead to a big number of conditions files.

>     * Should the configuration parameters common to all subject (all go through cond1, then cond2, ...), or can we have some parameters that change from a subject to another?

I would say one common for all the subjects.

**Comment by aremazeilles** [comment]
So we should go for `cond`, is this ok?

**Comment by alfonsotecnalia** [comment]
yes

**Comment by aremazeilles** [comment]
OK, working on it
