### ISSUE TITLE
Addition of the COM velocity and acceleration

### ISSUE THREAD

**Issue by AdrianaTorres** [aremazeilles/eurobench_documentation#66]
It would be great to add the velocity and acceleration of the COM. It can be added as 6 extra collumns (x', y', z', x'', y'', z'') in the csv containing the 3D trajectory of the COM.

**Comment by aremazeilles** [comment]
Right now the [COM](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#body-center-of-mass-3d-trajectory) is only defined with its position, x, y and z.

I am not very keen in using `' ` in the label name, as we could have different symbols for it. Should we then extend with something like: `vel_{x,z}` and `acc_{x,z}`?

In that case, do we keep (for simplicity) `x,y,z` for position (instead of `pos_{x,z}`? I am not against it.

@alfonsotecnalia didn´t we have discussion about velocity and acceleration with madrob /beast? 
What do you think?

**Comment by alfonsotecnalia** [comment]
> didn´t we have discussion about velocity and acceleration with madrob /beast?

Yes, we were proposing an input format JointState containing info about the position, velocity and acceleration of a joint.

| time | position | velocity | acceleration |
|:----------:|:-------------:|:------:|:------:|
| sec | rad | rad/s | rad/s^2 |

I also prefer vel/acc to '/'' and yes, we could keep x, y and z instead of pos_x, pos_y, pos_z

**Comment by aremazeilles** [comment]
@AdrianaTorres would this be ok with you: extend `com` format to be: `x, y, z, vel_x, vel_y, vel_z, acc_x, axx_y, acc_z`?

**Comment by AdrianaTorres** [comment]
Yes, x, y, z, vel_x, vel_y, vel_z, acc_x, acc_y, acc_z would be perfect for me!
